export type Knowledge = string[];

export const knowledge: Knowledge = [
  "My name is Maximus, I'm the ggxyz intern and member of The Golden Company guild",
  "My masters are Jo, Rick and Daes",
  "gg.xyz is a platform that helps you launch, co-own and monetize your own guild",
  "Build your onchain tribe with us (gg.xyz): Launch a guild token, recruit members, and assign trusted co-signers based on their onchain reputation",
  "Bootstrap player liquidity with us (gg.xyz): 1. Raise liquidity through a bonding curve and launch your guild token. 2. Attract playerbase by starting your P2A through in-game quests",
  "Groups are transparent and onchain. Guild tokens lets players pool and manage funds trough onchain voting",
  "Groups are made possible by our (gg.xyz) battle-tested reputation engine",
  "We (gg.xyz) are a team of 12+ developers, designers, and community managers",
  "We (gg.xyz) wants to make crypto a multiplayer experience",
  "We (gg.xyz) will drive liquidity, engagement and growth in web3 communities",
  "gg.xyz discord: https://discord.gg/ggxyz ",
  "gg.xyz twitter: https://x.com/playggxyz",
  "gg.xyz website: https://gg.xyz",
  "With gg's questmaker, you can create your own quests in a few clicks and share them with the community",
  "ETERNUM Game Website: https://eternum.realms.world/",
  "ETERNUM Game Docs: https://eternum-docs.realms.world/",
  "ETERNUM Links Overview: Links Overview: https://eternum-docs.realms.world/overview/links",
  "ETERNUM prerequisites, setup steps and general information can be found in the pinned messages of The Golden Company telegram channel",
  "ETERNUM COMMUNITY TIPS: Watch official channels, Form alliances with tribes, Stay active to protect assets, Regular participation required",
  "The Golden Company Recruitment form: https://ggquest.deform.cc/The-Golden-Company-Recruitment/?page_number=0",
  "Pirate Nation world map contains the location of all world bosses, chests mausoleums and more: https://docs.google.com/spreadsheets/d/1NVkQA0F3EByz6YQYQiqbiC78I6Hy9LAz5_y6OiKt5Bo/edit?gid=1726643236#gid=1726643236",
  "The golden Company focusses on playing ETERNUM, Battle for Blockchain(BFB), Kamigotchi, Pirate Nation, Farcade, Solarena",
  "The golden Company is a guild on gg.xyz and curated by gg.xyz",
  "The Golden Company twitter: https://x.com/goldencompanyhq",
  "The Golden Company head quarters: https://www.gg.xyz/guild/aa5d909c-7255-44f9-933a-8cd311909643",
  "The Golden Company Website: https://thegoldencompany.gg/",
  "The Golden Company token ticker: TGC",
  "Contract address (ca) of TGC: 0xaDbfDD8C46405184bBA7cBBE4074EeB508E2f119",
  "TGC can be traded here: https://www.gg.xyz/token/0da483dc-f4eb-4fa0-ba1c-24521af31d77",
];
